import { MainLayout } from "@/layouts/mainLayout";
import "./reset.css";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <head></head>
            <body>
                <MainLayout>{children}</MainLayout>
            </body>
        </html>
    );
}
